twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        test: 'je suis un test'
        cats: '@App\Twig\CatsExtension'
        
when@test:
    twig:
        strict_variables: true

   