controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
get_utls:
    path: /sitemap
    controller: App\Controller\SitemapController::index
    defaults: { _format: xml }    
